# Generated by Django 3.0.8 on 2020-07-18 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 0, 21, 49, 397615, tzinfo=utc))),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
