# Generated by Django 3.0.8 on 2020-07-18 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='year_in_school',
            field=models.CharField(choices=[('Ani', 'Animal'), ('Fd', 'Food'), ('Oth', 'Other')], default='Oth', max_length=20),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 0, 39, 1, 155341, tzinfo=utc)),
        ),
    ]
