# Generated by Django 3.0.8 on 2020-07-18 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200718_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='year_in_school',
            new_name='classes',
        ),
        migrations.AlterField(
            model_name='vocab',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 0, 39, 38, 531830, tzinfo=utc)),
        ),
    ]
