# Generated by Django 3.0.8 on 2020-07-19 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200718_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='chinese',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 1, 12, 27, 333178, tzinfo=utc)),
        ),
    ]
